#file: noinspection SpellCheckingInspection
name: Build and Release
on:
  release:
    types:
      - created
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v4

#      - name: install maker-flatpak dependencies
#        run: |
#          sudo apt-get install flatpak -y
#          sudo apt-get install flatpak-builder -y
#          sudo apt-get install elfutils -y
#          sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
#          sudo flatpak install flathub org.freedesktop.Platform/x86_64/19.08 org.freedesktop.Sdk/x86_64/19.08 org.electronjs.Electron2.BaseApp/x86_64/stable -y

      - name: Install dependencies
        run: |
          yarn
          yarn version --no-git-tag-version --new-version ${{ github.event.release.tag_name }}

      - name: Build for Linux
        run: yarn make --platform linux



      - name: Upload Zip to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/make/deb/x64/vtt-desktop-client_${{ github.event.release.tag_name }}_amd64.deb
          asset_name: vtt-desktop-client_${{ github.event.release.tag_name }}_amd64.deb
          asset_content_type: application/zip

      - name: Upload Zip to Release 2
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/make/rpm/x64/vtt-desktop-client-${{ github.event.release.tag_name }}-1.x86_64.rpm
          asset_name: vtt-desktop-client-${{ github.event.release.tag_name }}-1.x86_64.rpm
          asset_content_type: application/zip
      - name: Upload Zip to Release 3
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/make/zip/linux/x64/vtt-desktop-client-linux-x64-${{ github.event.release.tag_name }}.zip
          asset_name: vtt-desktop-client-linux-x64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

#      - name: Upload to Flathub
#        uses: flatpak/flatpak-github-actions/flat-manager@v4
#        with:
#          repository: elementary
#          flat-manager-url: https://flatpak-api.elementary.io
#          token: some_very_hidden_token
#          end-of-life: "The application has been renamed to..."
#          end-of-life-rebase: "org.zbrown.Palette"


  build-macos:
    runs-on: macos-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn
          yarn version --no-git-tag-version --new-version ${{ github.event.release.tag_name }}

      - name: Build for macOS
        run: yarn make --platform darwin

      - name: Upload Zip to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/make/zip/darwin/x64/vtt-desktop-client-darwin-x64-${{ github.event.release.tag_name }}.zip
          asset_name: vtt-desktop-client-macos-x64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: Upload Zip to Release 2
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/make/vtt-desktop-client-${{ github.event.release.tag_name }}-x64.dmg
          asset_name: vtt-desktop-client-${{ github.event.release.tag_name }}-x64.dmg
          asset_content_type: application/zip

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          yarn
          yarn version --no-git-tag-version --new-version ${{ github.event.release.tag_name }}

      - name: Build for Windows
        run: yarn make --platform win32

      - name: Zip Make Folder
        run: |
          $outputPath = "$PWD\out\win64.zip"
          Compress-Archive -Path "out\make\squirrel.windows\x64" -DestinationPath $outputPath

      - name: Upload Zip to Release
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out/win64.zip
          asset_name: vtt-desktop-client-windows-x64-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip
      - name: Upload Zip to Release 2
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: out\make\zip\win32\x64\vtt-desktop-client-win32-x64-${{ github.event.release.tag_name }}.zip
          asset_name: vtt-desktop-client-windows-x64-portable-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip